import type {
  Member,
  HelpRequest,
  VolunteerApplication,
  CaseAssignment,
  AdminMessage,
  AuditLogEntry,
  HelpDeskStats,
  Business,
  BusinessContactRequest,
  EBook,
  VideoWorkshop,
  ContentTemplate,
  CommunityEvent,
  TeamMember,
  NewsArticle,
  DonationCampaign,
  JobPosting,
} from '@/types';

// ========== MEMBERS ==========
export const mockMembers: Member[] = [
  {
    id: 'm1', firstName: 'Priya', lastName: 'Sharma', email: 'priya.sharma@gmail.com', phone: '+1-416-555-0101',
    pcNumber: 'PC-2025-0042', city: 'Toronto', province: 'Ontario', preferredLanguage: 'English',
    preferredContactMethod: 'portal', roleFlags: { isHelpSeeker: true, isVolunteer: false },
    verificationStatus: 'verified', accountStatus: 'active',
    createdAt: '2025-11-15T10:00:00Z', updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'm2', firstName: 'Arjun', lastName: 'Patel', email: 'arjun.patel@gmail.com', phone: '+1-604-555-0202',
    pcNumber: 'PC-2025-0108', city: 'Vancouver', province: 'British Columbia', preferredLanguage: 'English',
    preferredContactMethod: 'email', roleFlags: { isHelpSeeker: true, isVolunteer: true },
    verificationStatus: 'verified', accountStatus: 'active',
    createdAt: '2025-12-01T10:00:00Z', updatedAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'm3', firstName: 'Neha', lastName: 'Gupta', email: 'neha.gupta@gmail.com', phone: '+1-647-555-0303',
    pcNumber: 'PC-2026-0015', city: 'Toronto', province: 'Ontario', preferredLanguage: 'Hindi',
    preferredContactMethod: 'portal', roleFlags: { isHelpSeeker: true, isVolunteer: false },
    verificationStatus: 'pending', accountStatus: 'active',
    createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-04-05T08:00:00Z',
  },
  {
    id: 'm4', firstName: 'Raj', lastName: 'Kumar', email: 'raj.kumar@outlook.com', phone: '+1-613-555-0404',
    pcNumber: 'PC-2025-0003', city: 'Ottawa', province: 'Ontario', preferredLanguage: 'English',
    preferredContactMethod: 'portal', roleFlags: { isHelpSeeker: false, isVolunteer: true },
    verificationStatus: 'verified', accountStatus: 'active',
    createdAt: '2025-08-01T10:00:00Z', updatedAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'm5', firstName: 'Meera', lastName: 'Joshi', email: 'meera.joshi@gmail.com', phone: '+1-519-555-0505',
    city: 'Waterloo', province: 'Ontario', preferredLanguage: 'English',
    preferredContactMethod: 'email', roleFlags: { isHelpSeeker: false, isVolunteer: true },
    verificationStatus: 'verified', accountStatus: 'active',
    createdAt: '2025-07-20T10:00:00Z', updatedAt: '2026-04-08T08:00:00Z',
  },
];

// ========== HELP REQUESTS ==========
export const mockHelpRequests: HelpRequest[] = [
  {
    id: 'HR-2026-001', memberId: 'm1', memberName: 'Priya Sharma',
    category: 'Job Referrals and Placement Assistance', title: 'Looking for Software Engineering referrals at Shopify',
    description: 'I have 7 years experience building scalable platform infrastructure. I am looking for a Senior or Staff level role at Shopify. I would appreciate any referral assistance from someone connected to their engineering team.',
    urgency: 'medium', preferredTimeline: '2-4 weeks', previouslyRequested: false,
    documentsRequired: true, documents: ['priya_resume_2026.pdf'], consentGiven: true,
    supportType: 'one_time', openToGroupResources: false, contactByAdminOnly: true,
    status: 'assigned', assignedAdminId: 'admin1', assignedVolunteerId: 'm4', assignedVolunteerName: 'Raj Kumar',
    internalNotes: [
      { id: 'n1', authorId: 'admin1', authorName: 'Admin', body: 'Strong candidate. Raj Kumar has Shopify connections. Assigning.', createdAt: '2026-03-16T09:00:00Z' }
    ],
    timeline: [
      { date: '2026-03-15T10:00:00Z', status: 'submitted', description: 'Help request submitted by Priya Sharma' },
      { date: '2026-03-15T14:00:00Z', status: 'under_review', description: 'Admin reviewing request details' },
      { date: '2026-03-16T09:00:00Z', status: 'approved', description: 'Request approved by admin' },
      { date: '2026-03-16T09:30:00Z', status: 'assigned', description: 'Assigned to volunteer Raj Kumar' },
    ],
    createdAt: '2026-03-15T10:00:00Z', updatedAt: '2026-03-16T09:30:00Z',
  },
  {
    id: 'HR-2026-002', memberId: 'm3', memberName: 'Neha Gupta',
    category: 'Newcomer Settlement Support', title: 'Help with finding housing in Toronto',
    description: 'I recently arrived in Canada on a PGWP. I need guidance on finding affordable housing in the Greater Toronto Area. I have been looking at rental listings but I am not sure about tenant rights and what to look for in a lease.',
    urgency: 'high', preferredTimeline: '1-2 weeks', previouslyRequested: false,
    documentsRequired: false, documents: [], consentGiven: true,
    supportType: 'one_time', openToGroupResources: true, contactByAdminOnly: true,
    status: 'under_review', assignedAdminId: 'admin1',
    internalNotes: [
      { id: 'n2', authorId: 'admin1', authorName: 'Admin', body: 'Newcomer case. Check if Meera is available for settlement guidance.', createdAt: '2026-04-06T10:00:00Z' }
    ],
    timeline: [
      { date: '2026-04-05T15:00:00Z', status: 'submitted', description: 'Help request submitted by Neha Gupta' },
      { date: '2026-04-06T09:00:00Z', status: 'under_review', description: 'Admin reviewing request' },
    ],
    createdAt: '2026-04-05T15:00:00Z', updatedAt: '2026-04-06T10:00:00Z',
  },
  {
    id: 'HR-2026-003', memberId: 'm2', memberName: 'Arjun Patel',
    category: 'Tax Consultation', title: 'First-time filing Canadian taxes as a PR',
    description: 'I became a permanent resident in 2025. This is my first time filing taxes in Canada and I need help understanding RRSP, TFSA, and whether I should declare my foreign income from India.',
    urgency: 'medium', preferredTimeline: 'Before April 30', previouslyRequested: false,
    documentsRequired: true, documents: ['t4_slip.pdf', 'india_income_cert.pdf'], consentGiven: true,
    supportType: 'one_time', openToGroupResources: true, contactByAdminOnly: true,
    status: 'response_sent', assignedAdminId: 'admin1', assignedVolunteerId: 'm5', assignedVolunteerName: 'Meera Joshi',
    internalNotes: [
      { id: 'n3', authorId: 'admin1', authorName: 'Admin', body: 'Tax case. Meera has CPA background. Added disclaimer about non-professional advice.', createdAt: '2026-03-22T11:00:00Z' },
    ],
    timeline: [
      { date: '2026-03-20T09:00:00Z', status: 'submitted', description: 'Help request submitted' },
      { date: '2026-03-20T14:00:00Z', status: 'under_review', description: 'Admin reviewing' },
      { date: '2026-03-21T10:00:00Z', status: 'approved', description: 'Request approved' },
      { date: '2026-03-22T11:00:00Z', status: 'assigned', description: 'Assigned to Meera Joshi' },
      { date: '2026-03-25T16:00:00Z', status: 'volunteer_responded', description: 'Volunteer submitted guidance' },
      { date: '2026-03-26T09:00:00Z', status: 'admin_reviewing', description: 'Admin reviewing volunteer response' },
      { date: '2026-03-26T14:00:00Z', status: 'response_sent', description: 'Response sent to member by admin' },
    ],
    createdAt: '2026-03-20T09:00:00Z', updatedAt: '2026-03-26T14:00:00Z',
  },
  {
    id: 'HR-2026-004', memberId: 'm1', memberName: 'Priya Sharma',
    category: 'Resume and Cover Letter Review', title: 'Need resume review for senior engineering roles',
    description: 'I would like an experienced reviewer to look at my resume targeting senior+ engineering roles at top Canadian tech companies. I need feedback on layout, impact-driven bullet points, and overall positioning.',
    urgency: 'low', previouslyRequested: false,
    documentsRequired: true, documents: ['priya_resume_draft_v3.pdf'], consentGiven: true,
    supportType: 'one_time', openToGroupResources: false, contactByAdminOnly: true,
    status: 'resolved',
    internalNotes: [],
    timeline: [
      { date: '2026-02-10T09:00:00Z', status: 'submitted', description: 'Request submitted' },
      { date: '2026-02-11T10:00:00Z', status: 'assigned', description: 'Assigned to volunteer' },
      { date: '2026-02-15T14:00:00Z', status: 'response_sent', description: 'Feedback sent to member' },
      { date: '2026-02-16T08:00:00Z', status: 'resolved', description: 'Member confirmed resolution' },
    ],
    createdAt: '2026-02-10T09:00:00Z', updatedAt: '2026-02-16T08:00:00Z', closedAt: '2026-02-16T08:00:00Z',
  },
  {
    id: 'HR-2026-005', memberId: 'm3', memberName: 'Neha Gupta',
    category: 'Immigration Queries', title: 'PGWP to PR pathway guidance',
    description: 'My post-graduation work permit expires in 8 months. I need guidance on the Express Entry process, CRS score optimization, and whether I should apply through the Canadian Experience Class.',
    urgency: 'high', preferredTimeline: 'As soon as possible', previouslyRequested: false,
    documentsRequired: false, documents: [], consentGiven: true,
    supportType: 'ongoing_mentorship', openToGroupResources: true, contactByAdminOnly: true,
    status: 'submitted',
    internalNotes: [],
    timeline: [
      { date: '2026-04-14T10:00:00Z', status: 'submitted', description: 'Help request submitted by Neha Gupta' },
    ],
    createdAt: '2026-04-14T10:00:00Z', updatedAt: '2026-04-14T10:00:00Z',
  },
];

// ========== VOLUNTEER APPLICATIONS ==========
export const mockVolunteerApplications: VolunteerApplication[] = [
  {
    id: 'VA-001', memberId: 'm4', memberName: 'Raj Kumar',
    email: 'raj.kumar@outlook.com', phone: '+1-613-555-0404', pcNumber: 'PC-2025-0003',
    city: 'Ottawa', province: 'Ontario', linkedinUrl: 'linkedin.com/in/rajkumar',
    currentProfession: 'Staff Software Engineer', organization: 'Shopify', yearsExperience: 12,
    expertiseAreas: ['Job Referrals and Placement Assistance', 'Resume and Cover Letter Review', 'Career Guidance and Mentorship'],
    languages: ['English', 'Hindi', 'Punjabi'], availability: 'Weekday evenings, Saturdays',
    maxCasesPerMonth: 4, mentorshipInterest: true, referralSupportInterest: true,
    resumeReviewInterest: true, settlementSupportInterest: false, taxGuidanceInterest: false, immigrationGuidanceInterest: false,
    motivation: 'I want to give back to the community that helped me when I first arrived in Canada 8 years ago.',
    experienceSummary: '12 years in software engineering, currently Staff Engineer at Shopify. Have mentored 20+ engineers.',
    documents: ['raj_kumar_cv.pdf'], agreedToRules: true, agreedNoDirectContact: true, agreedAdminMediated: true, consentToScreening: true,
    status: 'approved', reviewedByAdminId: 'admin1', reviewedAt: '2025-09-01T10:00:00Z',
    adminNotes: 'Excellent candidate. Strong community commitment. Approved.',
    createdAt: '2025-08-15T10:00:00Z', updatedAt: '2025-09-01T10:00:00Z',
  },
  {
    id: 'VA-002', memberId: 'm5', memberName: 'Meera Joshi',
    email: 'meera.joshi@gmail.com', phone: '+1-519-555-0505',
    city: 'Waterloo', province: 'Ontario', linkedinUrl: 'linkedin.com/in/meerajoshi',
    currentProfession: 'CPA & Financial Advisor', organization: 'Independent', yearsExperience: 8,
    expertiseAreas: ['Tax Consultation', 'Newcomer Settlement Support', 'General Community Support'],
    languages: ['English', 'Hindi', 'Marathi'], availability: 'Flexible',
    maxCasesPerMonth: 6, mentorshipInterest: true, referralSupportInterest: false,
    resumeReviewInterest: false, settlementSupportInterest: true, taxGuidanceInterest: true, immigrationGuidanceInterest: false,
    motivation: 'As a CPA, I see many newcomers struggling with Canadian tax obligations. I want to help them navigate this.',
    experienceSummary: '8 years as CPA. Specialized in newcomer tax filing and cross-border tax issues.',
    documents: ['meera_cpa_cert.pdf', 'meera_cv.pdf'], agreedToRules: true, agreedNoDirectContact: true, agreedAdminMediated: true, consentToScreening: true,
    status: 'approved', reviewedByAdminId: 'admin1', reviewedAt: '2025-10-15T10:00:00Z',
    adminNotes: 'CPA credentials verified. Approved for tax and settlement categories.',
    createdAt: '2025-10-01T10:00:00Z', updatedAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'VA-003', memberId: 'm2', memberName: 'Arjun Patel',
    email: 'arjun.patel@gmail.com', phone: '+1-604-555-0202', pcNumber: 'PC-2025-0108',
    city: 'Vancouver', province: 'British Columbia', linkedinUrl: 'linkedin.com/in/arjunpatel',
    currentProfession: 'Product Manager', organization: 'Amazon Canada', yearsExperience: 5,
    expertiseAreas: ['Career Guidance and Mentorship', 'Resume and Cover Letter Review'],
    languages: ['English', 'Hindi', 'Gujarati'], availability: 'Weekends only',
    maxCasesPerMonth: 2, mentorshipInterest: true, referralSupportInterest: true,
    resumeReviewInterest: true, settlementSupportInterest: false, taxGuidanceInterest: false, immigrationGuidanceInterest: false,
    motivation: 'I benefited from mentorship when I transitioned to Canada. I want to pay it forward.',
    experienceSummary: '5 years as PM. Previously co-founded a startup. MBA from Rotman.',
    documents: ['arjun_cv.pdf'], agreedToRules: true, agreedNoDirectContact: true, agreedAdminMediated: true, consentToScreening: true,
    status: 'pending_verification', adminNotes: 'Need to verify Amazon employment.',
    createdAt: '2026-04-10T10:00:00Z', updatedAt: '2026-04-10T10:00:00Z',
  },
];

// ========== CASE ASSIGNMENTS ==========
export const mockAssignments: CaseAssignment[] = [
  {
    id: 'ASG-001', requestId: 'HR-2026-001', requestTitle: 'Looking for Software Engineering referrals at Shopify',
    volunteerMemberId: 'm4', volunteerName: 'Raj Kumar', assignedByAdminId: 'admin1',
    scope: 'Provide referral guidance and share relevant job openings at Shopify. Do NOT share personal contact details with the requester.',
    instructions: 'Review the member\'s resume and provide feedback. If appropriate, check internal openings. Respond through the admin relay only.',
    dueDate: '2026-03-23T00:00:00Z', status: 'in_progress',
    createdAt: '2026-03-16T09:30:00Z', updatedAt: '2026-03-18T14:00:00Z',
  },
  {
    id: 'ASG-002', requestId: 'HR-2026-003', requestTitle: 'First-time filing Canadian taxes as a PR',
    volunteerMemberId: 'm5', volunteerName: 'Meera Joshi', assignedByAdminId: 'admin1',
    scope: 'Provide general tax filing guidance for first-time PR filers. Include RRSP/TFSA basics, foreign income declaration overview.',
    instructions: 'NOTE: Add disclaimer that this is general guidance, not professional tax advice. Member should consult a CPA for formal filing.',
    dueDate: '2026-03-30T00:00:00Z', status: 'completed',
    volunteerResponse: 'I\'ve prepared a comprehensive guide covering: 1) T4 filing basics, 2) RRSP vs TFSA comparison, 3) Foreign income declaration requirements under the ITA. Included the standard disclaimer. Ready for admin review.',
    createdAt: '2026-03-22T11:00:00Z', updatedAt: '2026-03-26T14:00:00Z',
  },
];

// ========== ADMIN MESSAGES ==========
export const mockMessages: AdminMessage[] = [
  {
    id: 'msg-001', caseId: 'HR-2026-001', caseTitle: 'Looking for Software Engineering referrals at Shopify',
    senderRole: 'admin', senderUserId: 'admin1', senderName: 'Admin',
    recipientRole: 'member', moderatedFlag: false, visibilityScope: 'member_only',
    body: 'Hi Priya, we have received your request for referral assistance at Shopify. We are currently matching you with a volunteer who has connections there. You will hear back within 3-5 business days.',
    attachments: [], read: true, createdAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'msg-002', caseId: 'HR-2026-001', caseTitle: 'Looking for Software Engineering referrals at Shopify',
    senderRole: 'member', senderUserId: 'm1', senderName: 'Priya Sharma',
    recipientRole: 'admin', moderatedFlag: false, visibilityScope: 'admin_only',
    body: 'Thank you for the update! I am happy to provide any additional information needed. Looking forward to hearing back.',
    attachments: [], read: true, createdAt: '2026-03-16T11:00:00Z',
  },
  {
    id: 'msg-003', caseId: 'HR-2026-003', caseTitle: 'First-time filing Canadian taxes as a PR',
    senderRole: 'admin', senderUserId: 'admin1', senderName: 'Admin',
    recipientRole: 'member', moderatedFlag: false, visibilityScope: 'member_only',
    body: 'Hi Arjun, our volunteer has prepared a comprehensive guide for your tax situation. Please find the guidance below:\n\n1. T4 Filing: File through CRA My Account. Your employer\'s T4 slip has all the info needed.\n2. RRSP: You have contribution room based on your 2025 earned income (18% of earned income, up to the annual limit).\n3. TFSA: As a PR, you accumulate room from the year you became a resident.\n4. Foreign Income: If you had Indian income in 2025, it must be declared. Canada-India tax treaty prevents double taxation.\n\nNOTICE: This is general guidance only and not professional tax advice. Please consult a licensed CPA for your specific filing.',
    attachments: ['tax_guide_newcomers.pdf'], read: false, createdAt: '2026-03-26T14:00:00Z',
  },
  {
    id: 'msg-004', caseId: 'HR-2026-002', caseTitle: 'Help with finding housing in Toronto',
    senderRole: 'admin', senderUserId: 'admin1', senderName: 'Admin',
    recipientRole: 'member', moderatedFlag: false, visibilityScope: 'member_only',
    body: 'Hi Neha, thank you for reaching out. We are currently reviewing your settlement support request. We have a volunteer with Toronto housing expertise and will connect you through our admin-mediated process shortly.',
    attachments: [], read: true, createdAt: '2026-04-06T10:30:00Z',
  },
  {
    id: 'msg-005', caseId: 'HR-2026-001', caseTitle: 'Looking for Software Engineering referrals at Shopify',
    senderRole: 'admin', senderUserId: 'admin1', senderName: 'Admin',
    recipientRole: 'volunteer', moderatedFlag: false, visibilityScope: 'volunteer_only',
    body: 'Hi Raj, we have a member looking for referral assistance at Shopify for a Senior/Staff SWE role. They have 7 years of experience. Please review the attached resume and let us know if you can help. Do NOT contact the member directly.',
    attachments: ['priya_resume_2026.pdf'], read: true, createdAt: '2026-03-16T09:45:00Z',
  },
];

// ========== AUDIT LOG ==========
export const mockAuditLog: AuditLogEntry[] = [
  { id: 'log-001', actorId: 'admin1', actorName: 'Admin', actorRole: 'admin', actionType: 'request_reviewed', targetType: 'request', targetId: 'HR-2026-001', description: 'Reviewed and approved help request HR-2026-001', timestamp: '2026-03-16T09:00:00Z' },
  { id: 'log-002', actorId: 'admin1', actorName: 'Admin', actorRole: 'admin', actionType: 'volunteer_assigned', targetType: 'assignment', targetId: 'ASG-001', description: 'Assigned volunteer Raj Kumar to case HR-2026-001', timestamp: '2026-03-16T09:30:00Z' },
  { id: 'log-003', actorId: 'admin1', actorName: 'Admin', actorRole: 'admin', actionType: 'message_sent', targetType: 'message', targetId: 'msg-001', description: 'Sent acknowledgment message to Priya Sharma', timestamp: '2026-03-16T10:00:00Z' },
  { id: 'log-004', actorId: 'admin1', actorName: 'Admin', actorRole: 'admin', actionType: 'volunteer_approved', targetType: 'volunteer_app', targetId: 'VA-001', description: 'Approved volunteer application from Raj Kumar', timestamp: '2025-09-01T10:00:00Z' },
  { id: 'log-005', actorId: 'admin1', actorName: 'Admin', actorRole: 'admin', actionType: 'response_relayed', targetType: 'message', targetId: 'msg-003', description: 'Relayed volunteer tax guidance to Arjun Patel', timestamp: '2026-03-26T14:00:00Z' },
  { id: 'log-006', actorId: 'm1', actorName: 'Priya Sharma', actorRole: 'member', actionType: 'request_submitted', targetType: 'request', targetId: 'HR-2026-001', description: 'Submitted help request for Shopify referral', timestamp: '2026-03-15T10:00:00Z' },
  { id: 'log-007', actorId: 'm3', actorName: 'Neha Gupta', actorRole: 'member', actionType: 'request_submitted', targetType: 'request', targetId: 'HR-2026-005', description: 'Submitted help request for PGWP to PR guidance', timestamp: '2026-04-14T10:00:00Z' },
];

// ========== STATS ==========
export const mockStats: HelpDeskStats = {
  totalMembers: 247,
  totalRequests: 89,
  openRequests: 12,
  closedRequests: 64,
  pendingVolunteerApps: 3,
  approvedVolunteers: 18,
  activeAssignments: 5,
  avgResolutionDays: 4.2,
  escalations: 2,
  categoryCounts: {
    'Job Referrals and Placement Assistance': 28,
    'Resume and Cover Letter Review': 18,
    'Newcomer Settlement Support': 15,
    'Tax Consultation': 9,
    'Career Guidance and Mentorship': 8,
    'Immigration Queries': 5,
    'General Community Support': 4,
    'Other': 2,
  },
};

// ========== BUSINESSES ==========
export const mockBusinesses: Business[] = [
  {
    id: 'biz-001', name: 'Sharma & Associates CPA', slug: 'sharma-associates-cpa',
    logo: '', coverImage: '/finance_bg.png',
    category: 'Tax & Accounting', descriptionShort: 'Trusted tax filing and accounting for newcomers and professionals.',
    descriptionFull: 'Sharma & Associates is a full-service CPA firm specializing in personal and corporate tax filing for newcomers to Canada. With over 15 years of experience, we understand the unique tax situations faced by immigrants — from foreign income declaration to RRSP/TFSA optimization. Our team of 5 certified CPAs provides year-round support for individuals and small businesses across the GTA.',
    services: ['Personal Tax Filing', 'Corporate Tax Returns', 'GST/HST Filing', 'Bookkeeping', 'Financial Planning', 'Cross-Border Tax Advisory', 'CRA Audit Support'],
    contactPerson: 'Vikram Sharma, CPA', phone: '+1 (416) 555-0120', email: 'info@sharmacpa.ca', website: 'https://sharmacpa.ca',
    socialLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com/company/sharmacpa' }],
    address: '200 Bay Street, Suite 1200', city: 'Toronto', province: 'Ontario', postalCode: 'M5J 2J2', serviceArea: 'Greater Toronto Area',
    yearsInBusiness: 15, businessHours: 'Mon–Fri 9AM–6PM, Sat 10AM–2PM',
    pricingSummary: 'Personal returns from $80, Corporate from $500',
    memberRateText: '15% off all services for Professionals Club members', offerBadge: '15% Off',
    memberBenefits: ['15% discount on all tax services', 'Free 20-minute initial consultation', 'Priority scheduling during tax season', 'Free T1 review for first-time filers'],
    verificationStatus: 'verified', isFeatured: true, hasMemberRate: true,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2025-11-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'biz-002', name: 'Maple Leaf Immigration', slug: 'maple-leaf-immigration',
    logo: '', coverImage: '/toronto-skyline.png',
    category: 'Immigration Services', descriptionShort: 'RCIC-licensed immigration consultants helping you build your Canadian future.',
    descriptionFull: 'Maple Leaf Immigration is a licensed RCIC firm with a 95% application success rate. We help professionals navigate Express Entry, PNP programs, work permits, PR applications, citizenship, and spousal sponsorship. Our consultants have processed over 2,000 successful applications and specialize in helping Indian professionals transition to permanent residency.',
    services: ['Express Entry Applications', 'Provincial Nominee Programs', 'Work Permit Extensions', 'PR Applications', 'Citizenship Applications', 'Spousal Sponsorship', 'LMIA Processing', 'Study Permits'],
    contactPerson: 'Anita Mehta, RCIC', phone: '+1 (647) 555-0230', email: 'consult@mapleleafimmigration.ca', website: 'https://mapleleafimmigration.ca',
    socialLinks: [{ platform: 'Instagram', url: 'https://instagram.com/mapleleafimmigration' }],
    address: '4950 Yonge Street, Suite 800', city: 'Toronto', province: 'Ontario', postalCode: 'M2N 6K1', serviceArea: 'All of Canada (virtual)',
    yearsInBusiness: 8, businessHours: 'Mon–Fri 10AM–7PM',
    pricingSummary: 'Consultations from $150, Full-service PR from $3,500',
    memberRateText: 'Free 30-minute consultation + 10% off full-service packages', offerBadge: 'Free Consult',
    memberBenefits: ['Free 30-minute initial assessment', '10% off full-service immigration packages', 'Priority application review', 'Free CRS score assessment'],
    verificationStatus: 'verified', isFeatured: false, hasMemberRate: true,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2025-12-15T10:00:00Z', updatedAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'biz-003', name: 'HomeTrust Realty', slug: 'hometrust-realty',
    logo: '', coverImage: '/housing_bg.png',
    category: 'Real Estate', descriptionShort: 'Helping newcomers find their first Canadian home with confidence.',
    descriptionFull: 'HomeTrust Realty specializes in helping newcomers and first-time buyers navigate the Canadian real estate market. Our team of 8 multilingual agents (English, Hindi, Punjabi, Tamil) understands the unique challenges faced by immigrants — from understanding mortgage pre-approvals to navigating bidding wars. We cover all of the GTA and have helped 500+ families find their homes.',
    services: ['Buyer Representation', 'Seller Representation', 'Newcomer Home Search', 'Investment Properties', 'Pre-Construction Sales', 'Rental Assistance', 'Market Analysis'],
    contactPerson: 'Deepak Verma', phone: '+1 (416) 555-0345', email: 'deepak@hometrustrealty.ca', website: 'https://hometrustrealty.ca',
    socialLinks: [{ platform: 'YouTube', url: 'https://youtube.com/@hometrustrealty' }],
    address: '100 King Street West, Suite 500', city: 'Toronto', province: 'Ontario', postalCode: 'M5X 1A9', serviceArea: 'GTA, Peel, York, Durham',
    yearsInBusiness: 12, businessHours: 'Mon–Sun 9AM–8PM',
    pricingSummary: 'Standard commission rates apply',
    memberRateText: 'Cashback rebate of 0.5% on closing for PC members', offerBadge: 'Cashback',
    memberBenefits: ['0.5% cashback rebate at closing', 'Free home valuation report', 'Dedicated multilingual agent', 'Free newcomer home-buying guide'],
    verificationStatus: 'verified', isFeatured: true, hasMemberRate: true,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2025-10-01T10:00:00Z', updatedAt: '2026-04-05T10:00:00Z',
  },
  {
    id: 'biz-004', name: 'NorthStar Insurance', slug: 'northstar-insurance',
    logo: '', coverImage: '/hero-community.png',
    category: 'Insurance', descriptionShort: 'Auto, home, life, and health insurance tailored for newcomers.',
    descriptionFull: 'NorthStar Insurance provides comprehensive insurance solutions for newcomers and established professionals. We partner with 15+ top Canadian insurance carriers to find you the best rates. Our advisors understand newcomer-specific needs like securing auto insurance without Canadian driving history, and visitor health coverage for visiting parents.',
    services: ['Auto Insurance', 'Home Insurance', 'Life Insurance', 'Health & Dental', 'Visitor Insurance', 'Travel Insurance', 'Business Insurance', 'Disability Insurance'],
    contactPerson: 'Kavita Singh', phone: '+1 (905) 555-0456', email: 'kavita@northstarinsurance.ca', website: 'https://northstarinsurance.ca',
    socialLinks: [],
    address: '3100 Steeles Ave East', city: 'Markham', province: 'Ontario', postalCode: 'L3R 8T3', serviceArea: 'Ontario-wide',
    yearsInBusiness: 6, businessHours: 'Mon–Fri 9AM–6PM',
    pricingSummary: 'Auto from $120/mo, Home from $40/mo',
    verificationStatus: 'verified', isFeatured: false, hasMemberRate: false,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2026-01-10T10:00:00Z', updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'biz-005', name: 'CloudBridge Solutions', slug: 'cloudbridge-solutions',
    logo: '', coverImage: '/career-mentorship.png',
    category: 'IT Services', descriptionShort: 'Web development, cloud infrastructure, and IT consulting for businesses.',
    descriptionFull: 'CloudBridge Solutions is a boutique IT consulting firm run by experienced professionals from the Indian tech community. We build websites, mobile apps, and cloud infrastructure for startups and small businesses. Our team has delivered 100+ projects for clients across Canada, with expertise in AWS, Azure, React, and Node.js.',
    services: ['Website Development', 'Mobile App Development', 'Cloud Migration (AWS/Azure)', 'IT Consulting', 'DevOps & CI/CD', 'UI/UX Design', 'Cybersecurity Audits', 'SaaS Product Development'],
    contactPerson: 'Rohan Desai', phone: '+1 (647) 555-0567', email: 'hello@cloudbridge.ca', website: 'https://cloudbridge.ca',
    socialLinks: [{ platform: 'GitHub', url: 'https://github.com/cloudbridge' }, { platform: 'LinkedIn', url: 'https://linkedin.com/company/cloudbridge' }],
    address: '155 University Ave, Suite 400', city: 'Toronto', province: 'Ontario', postalCode: 'M5H 3B7', serviceArea: 'Canada-wide (remote)',
    yearsInBusiness: 4, businessHours: 'Mon–Fri 9AM–6PM',
    pricingSummary: 'Projects from $5,000, Consulting from $150/hr',
    memberRateText: '20% off first project for PC members', offerBadge: '20% Off',
    memberBenefits: ['20% discount on first project', 'Free 1-hour technical consultation', 'Priority support queue', 'Monthly tech office hours for members'],
    verificationStatus: 'verified', isFeatured: false, hasMemberRate: true,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'biz-006', name: 'Notary Express GTA', slug: 'notary-express-gta',
    logo: '', coverImage: '/settlement-guide.png',
    category: 'Notary / Documentation', descriptionShort: 'Fast, reliable notary and documentation services across the GTA.',
    descriptionFull: 'Notary Express GTA provides commissioner of oaths and notary public services for all document types. We specialize in immigration documents, affidavits, statutory declarations, and powers of attorney. Walk-in and mobile service available. We understand the urgency of document deadlines for immigration cases.',
    services: ['Notarization', 'Commissioner of Oaths', 'Affidavits', 'Statutory Declarations', 'Power of Attorney', 'Document Certification', 'Apostille Assistance', 'Mobile Notary Service'],
    contactPerson: 'Suresh Iyer', phone: '+1 (416) 555-0678', email: 'service@notaryexpress.ca', website: 'https://notaryexpress.ca',
    socialLinks: [],
    address: '40 Dundas Street West, Suite 300', city: 'Toronto', province: 'Ontario', postalCode: 'M5G 2C2', serviceArea: 'GTA + Mobile Service',
    yearsInBusiness: 10, businessHours: 'Mon–Sat 9AM–7PM',
    pricingSummary: 'Notarization from $25/document',
    verificationStatus: 'verified', isFeatured: false, hasMemberRate: false,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'biz-007', name: 'Wellness Path Clinic', slug: 'wellness-path-clinic',
    logo: '', coverImage: '/healthcare_bg.png',
    category: 'Health & Wellness', descriptionShort: 'Holistic health services including physiotherapy, chiropractic, and wellness coaching.',
    descriptionFull: 'Wellness Path Clinic is a multidisciplinary health clinic offering physiotherapy, chiropractic care, massage therapy, naturopathy, and mental wellness support. Our practitioners provide culturally sensitive care and understand the health challenges common to newcomers, including stress, adjustment disorders, and musculoskeletal issues from desk jobs.',
    services: ['Physiotherapy', 'Chiropractic Care', 'Registered Massage Therapy', 'Naturopathy', 'Mental Wellness Counselling', 'Nutrition Counselling', 'Workplace Ergonomics'],
    contactPerson: 'Dr. Priya Nair', phone: '+1 (905) 555-0789', email: 'info@wellnesspath.ca', website: 'https://wellnesspath.ca',
    socialLinks: [{ platform: 'Instagram', url: 'https://instagram.com/wellnesspathclinic' }],
    address: '2200 Dundas Street East', city: 'Mississauga', province: 'Ontario', postalCode: 'L4X 1L9', serviceArea: 'Mississauga, Brampton, GTA',
    yearsInBusiness: 3, businessHours: 'Mon–Fri 8AM–8PM, Sat 9AM–4PM',
    pricingSummary: 'Initial assessment $85, Follow-ups from $65',
    memberRateText: 'Free initial assessment for PC members', offerBadge: 'Free Assessment',
    memberBenefits: ['Free initial health assessment ($85 value)', '10% off treatment packages', 'Extended evening appointments for members'],
    verificationStatus: 'pending_review', isFeatured: false, hasMemberRate: true,
    createdBy: 'admin1', createdAt: '2026-04-10T10:00:00Z', updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'biz-008', name: 'Elevate Financial Planning', slug: 'elevate-financial-planning',
    logo: '', coverImage: '/finance_bg.png',
    category: 'Financial Planning', descriptionShort: 'Wealth management and financial planning for professionals building their Canadian future.',
    descriptionFull: 'Elevate Financial Planning helps newcomer professionals build long-term wealth in Canada. From your first TFSA to comprehensive retirement planning, our certified financial planners create personalized strategies that account for cross-border assets, currency exchange optimization, and Canadian tax advantages. We manage portfolios from $25,000 to $5M+.',
    services: ['Financial Planning', 'Investment Management', 'RRSP/TFSA Strategy', 'RESP Planning', 'Insurance Needs Analysis', 'Retirement Planning', 'Cross-Border Wealth Transfer', 'Estate Planning'],
    contactPerson: 'Arun Kapoor, CFP', phone: '+1 (416) 555-0890', email: 'arun@elevatefinancial.ca', website: 'https://elevatefinancial.ca',
    socialLinks: [{ platform: 'LinkedIn', url: 'https://linkedin.com/in/arunkapoor' }],
    address: '1 Adelaide Street East, Suite 2800', city: 'Toronto', province: 'Ontario', postalCode: 'M5C 2V9', serviceArea: 'Ontario (virtual across Canada)',
    yearsInBusiness: 9, businessHours: 'Mon–Fri 9AM–6PM',
    pricingSummary: 'Financial plan from $500, Portfolio management 1% AUM',
    memberRateText: 'Complimentary financial health check + waived plan fee for first year', offerBadge: 'Free Plan',
    memberBenefits: ['Complimentary 1-hour financial health check', 'Waived financial plan fee ($500 value) for first year', 'Quarterly portfolio review calls', 'Access to member-only webinars on wealth building'],
    verificationStatus: 'verified', isFeatured: true, hasMemberRate: true,
    createdBy: 'admin1', approvedByAdmin: 'admin1', createdAt: '2025-09-01T10:00:00Z', updatedAt: '2026-04-12T10:00:00Z',
  },
];

// ========== BUSINESS CONTACT REQUESTS ==========
export const mockBusinessContactRequests: BusinessContactRequest[] = [
  {
    id: 'bcr-001', businessId: 'biz-001', businessName: 'Sharma & Associates CPA',
    memberId: 'm1', memberName: 'Priya Sharma', helpType: 'quote_support',
    preferredContact: 'email', notes: 'I need help understanding if I should file as a sole proprietor or incorporate. Would like admin to help me get a consultation scheduled.',
    status: 'pending', createdAt: '2026-04-14T10:00:00Z', updatedAt: '2026-04-14T10:00:00Z',
  },
  {
    id: 'bcr-002', businessId: 'biz-003', businessName: 'HomeTrust Realty',
    memberId: 'm3', memberName: 'Neha Gupta', helpType: 'introduction',
    preferredContact: 'phone', notes: 'I am looking for a 1-bedroom condo rental in downtown Toronto. Would appreciate an introduction to the agent who handles newcomer rentals.',
    status: 'in_progress', adminNotes: 'Connected with Deepak. Follow up on Friday.', createdAt: '2026-04-12T10:00:00Z', updatedAt: '2026-04-13T10:00:00Z',
  },
];

// ========== E-BOOKS ==========
export const mockEBooks: EBook[] = [
  { id: 'eb-001', title: "CPA's Guide to Canada", author: 'Professionals Club', type: 'PDF', size: '2.4 MB', color: '#6366f1', image: '/finance_bg.png', downloadUrl: '#', createdAt: '2026-01-15T10:00:00Z' },
  { id: 'eb-002', title: 'IT Careers in Ontario', author: 'Professionals Club', type: 'PDF', size: '1.8 MB', color: '#059669', image: '/career-mentorship.png', downloadUrl: '#', createdAt: '2026-02-01T10:00:00Z' },
  { id: 'eb-003', title: 'Medical Licensing Roadmap', author: 'Professionals Club Health Team', type: 'PDF', size: '3.1 MB', color: '#dc2626', image: '/healthcare_bg.png', downloadUrl: '#', createdAt: '2026-02-15T10:00:00Z' },
  { id: 'eb-004', title: 'Engineering Success Path', author: 'Professionals Club Engineering', type: 'PDF', size: '2.0 MB', color: '#d97706', image: '/housing_bg.png', downloadUrl: '#', createdAt: '2026-03-01T10:00:00Z' },
];

// ========== VIDEO WORKSHOPS ==========
export const mockWorkshops: VideoWorkshop[] = [
  { id: 'ws-001', title: 'Learn Canadian Individual Taxes | Canada Tax Series | Lesson 1', duration: '57:22', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/meetup_bg.png', videoUrl: '#', createdAt: '2026-01-12T10:00:00Z' },
  { id: 'ws-002', title: 'Complete Guide : How to Become a Realtor in Canada in Year 2025', duration: '46:38', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/events-meetup.png', videoUrl: '#', createdAt: '2026-02-08T10:00:00Z' },
  { id: 'ws-003', title: 'How to Become a Mortgage Agent in Ontario?', duration: '24:54', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/housing_bg.png', videoUrl: '#', createdAt: '2026-03-15T10:00:00Z' },
  { id: 'ws-004', title: 'Sponsor Parents for Canadian PR Visa Myths and Super Visa', duration: '45 mins', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/career-mentorship.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
  { id: 'ws-005', title: 'ICP - Bajahan Sandhya in Toronto', duration: '0:51', recordedDate: '3 months ago', platform: 'YouTube', thumbnailImage: '/event_bg.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
  { id: 'ws-006', title: 'CPA Canada - CFE Strategy Session - May 2026', duration: '1:37:42', recordedDate: '6 months ago', platform: 'YouTube', thumbnailImage: '/healthcare_bg.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
  { id: 'ws-007', title: 'Partnership & Trust Tax Basics | Canada Tax Series', duration: '24:50', recordedDate: '7 months ago', platform: 'YouTube', thumbnailImage: '/hero-community.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
  { id: 'ws-008', title: 'CFA: Preparation, Strategy, and Career Pathways', duration: '45 mins', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/volunteer-help.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
  { id: 'ws-009', title: 'Declaring Bankruptcy and Saving Personal Assets', duration: '1:03:24', recordedDate: '1 year ago', platform: 'YouTube', thumbnailImage: '/finance_bg.png', videoUrl: '#', createdAt: '2026-04-02T10:00:00Z' },
];

// ========== TEMPLATES ==========
export const mockTemplates: ContentTemplate[] = [
  { id: 'tp-001', title: 'Standard Canadian Resume', fileType: 'Word Doc', category: 'Career', image: '/hero-community.png', accessUrl: '#', createdAt: '2026-01-01T10:00:00Z' },
  { id: 'tp-002', title: 'Professional Cover Letter', fileType: 'Word Doc', category: 'Career', image: '/volunteer-help.png', accessUrl: '#', createdAt: '2026-01-15T10:00:00Z' },
  { id: 'tp-003', title: 'Networking Message Templates', fileType: 'PDF', category: 'Communication', image: '/events-meetup.png', accessUrl: '#', createdAt: '2026-02-01T10:00:00Z' },
  { id: 'tp-004', title: 'Rental Application Bundle', fileType: 'ZIP', category: 'Settlement', image: '/settlement-guide.png', accessUrl: '#', createdAt: '2026-02-15T10:00:00Z' },
];

// ========== EVENTS ==========
export const mockEvents: CommunityEvent[] = [
  { id: 'evt-001', title: 'Toronto Monthly Community Meetup', description: 'An informal gathering to welcome newcomers, share settlement guidance, and expand professional networks.', date: '2026-04-25', time: '6:00 PM - 9:00 PM EST', location: 'Downtown Toronto', eventType: 'in_person', capacity: 60, attendees: 0, image: '/meetup_bg.png', isFeatured: true, rsvpUrl: '#', status: 'upcoming', createdAt: '2026-04-01T10:00:00Z' },
  { id: 'evt-002', title: 'Taxes for Newcomers — Live Workshop', description: 'Weekly financial literacy and cultural adaptation guidance sessions online.', date: '2026-04-22', time: '7:00 PM EST', location: 'Online', eventType: 'virtual', capacity: 200, attendees: 0, image: '/finance_bg.png', isFeatured: false, platform: 'YouTube Live', status: 'upcoming', createdAt: '2026-04-10T10:00:00Z' },
  { id: 'evt-003', title: 'Resume Polish Workshop', description: 'Weekly resume review workshop for professionals.', date: '2026-04-24', time: '6:00 PM EST', location: 'Online', eventType: 'virtual', capacity: 50, attendees: 0, image: '/career-mentorship.png', isFeatured: false, platform: 'Zoom Meeting', status: 'upcoming', createdAt: '2026-04-10T10:00:00Z' },
  { id: 'evt-004', title: 'March 2026 — Toronto Meetup', description: 'Monthly networking event in downtown Toronto.', date: '2026-03-28', time: '6:00 PM - 9:00 PM EST', location: 'Downtown Toronto', eventType: 'in_person', capacity: 60, attendees: 45, image: '/event_bg.png', isFeatured: false, status: 'past', createdAt: '2026-03-01T10:00:00Z' },
  { id: 'evt-005', title: 'February 2026 — Tax Season Prep', description: 'Live YouTube workshop covering tax essentials for newcomers.', date: '2026-02-15', time: '7:00 PM EST', location: 'Online', eventType: 'virtual', capacity: 200, attendees: 120, image: '/events-meetup.png', isFeatured: false, platform: 'YouTube Live', status: 'past', createdAt: '2026-02-01T10:00:00Z' },
  { id: 'evt-006', title: 'January 2026 — New Year Networking', description: 'New year networking social event.', date: '2026-01-31', time: '6:00 PM - 9:00 PM EST', location: 'Downtown Toronto', eventType: 'in_person', capacity: 50, attendees: 38, image: '/event_bg.png', isFeatured: false, status: 'past', createdAt: '2026-01-15T10:00:00Z' },
  { id: 'evt-007', title: 'December 2025 — Holiday Social', description: 'End-of-year holiday social gathering.', date: '2025-12-20', time: '7:00 PM EST', location: 'Downtown Toronto', eventType: 'in_person', capacity: 80, attendees: 62, image: '/events-meetup.png', isFeatured: false, status: 'past', createdAt: '2025-12-01T10:00:00Z' },
  { id: 'evt-008', title: 'November 2025 — Resume Workshop', description: 'Practical resume review workshop via Zoom.', date: '2025-11-15', time: '6:00 PM EST', location: 'Online', eventType: 'virtual', capacity: 100, attendees: 95, image: '/event_bg.png', isFeatured: false, platform: 'Zoom', status: 'past', createdAt: '2025-11-01T10:00:00Z' },
  { id: 'evt-009', title: 'October 2025 — Immigration Q&A', description: 'Immigration Q&A with RCIC consultants.', date: '2025-10-18', time: '7:00 PM EST', location: 'Online', eventType: 'virtual', capacity: 300, attendees: 210, image: '/events-meetup.png', isFeatured: false, platform: 'YouTube Live', status: 'past', createdAt: '2025-10-01T10:00:00Z' },
];

// ========== TEAM MEMBERS ==========
export const mockTeamMembers: TeamMember[] = [
  { id: 'tm-001', name: 'Udit Gupta', role: 'Founder, CEO & Director', bio: 'Udit moved to Canada in 2019 and founded the Professionals Club initiative in August 2022 to simplify the integration process for newcomers.', image: '/hero-community.png', linkedinUrl: '#', order: 1, createdAt: '2025-01-01T10:00:00Z' },
  { id: 'tm-002', name: 'Priya Nair', role: 'Community Manager', bio: 'Priya oversees all community engagement initiatives, event planning, and member relations across Canada.', image: '/volunteer-help.png', linkedinUrl: '#', order: 2, createdAt: '2025-03-01T10:00:00Z' },
  { id: 'tm-003', name: 'Raj Malhotra', role: 'Head of Partnerships', bio: 'Raj leads business partnerships, ensuring verified directory listings and member benefit programs.', image: '/career-mentorship.png', linkedinUrl: '#', order: 3, createdAt: '2025-05-01T10:00:00Z' },
  { id: 'tm-004', name: 'Anita Sharma', role: 'Settlement Program Lead', bio: 'Anita coordinates settlement support services, connecting newcomers with trusted guidance and resources.', image: '/events-meetup.png', linkedinUrl: '#', order: 4, createdAt: '2025-06-01T10:00:00Z' },
];

// ========== NEWS ARTICLES ==========
export const mockNewsArticles: NewsArticle[] = [
  { id: 'news-001', title: 'Professionals Club Reaches 2,000 Members Milestone', summary: 'Our community has grown to over 2,000 active members across Canada, marking a significant milestone in our mission.', content: 'We are thrilled to announce that Professionals Club has officially reached 2,000 active members across Canada. This milestone reflects the growing demand for structured community support among Indian professionals and newcomers.', image: '/hero-community.png', author: 'Udit Gupta', category: 'Announcement', publishedAt: '2026-04-10T10:00:00Z', createdAt: '2026-04-10T10:00:00Z' },
  { id: 'news-002', title: 'Monthly Meetup Recap — March 2026', summary: '45 professionals gathered at our downtown Toronto meetup for networking and settlement guidance.', content: 'Our March 2026 Toronto meetup was another success, with 45 professionals coming together for an evening of networking, settlement guidance, and community building.', image: '/meetup_bg.png', author: 'Priya Nair', category: 'Events', publishedAt: '2026-03-30T10:00:00Z', createdAt: '2026-03-30T10:00:00Z' },
  { id: 'news-003', title: 'New Business Partnership — Sharma & Associates CPA', summary: 'We welcome Sharma & Associates CPA to our verified business directory with exclusive member rates.', content: 'Professionals Club is excited to welcome Sharma & Associates CPA as a verified partner in our business directory. Members now enjoy 15% off all tax services.', image: '/finance_bg.png', author: 'Raj Malhotra', category: 'Partnerships', publishedAt: '2026-03-15T10:00:00Z', createdAt: '2026-03-15T10:00:00Z' },
  { id: 'news-004', title: 'Tax Season 2026 — Free Resources Available', summary: 'Access our free tax filing guides, video workshops, and CPA consultation offers.', content: 'Tax season is here! Professionals Club has compiled a comprehensive set of free resources to help newcomers navigate their first Canadian tax filing.', image: '/events-meetup.png', author: 'Anita Sharma', category: 'Resources', publishedAt: '2026-03-01T10:00:00Z', createdAt: '2026-03-01T10:00:00Z' },
];

// ========== DONATION CAMPAIGNS ==========
export const mockDonationCampaigns: DonationCampaign[] = [
  { id: 'don-001', title: 'Support Our Community Engagement Efforts', description: 'As a non-profit dedicated to strengthening community ties, we invite you to contribute to our events that connect newcomers with local communities. Your donation helps us create more inclusive and vibrant community gatherings.', goalAmount: 10000, raisedAmount: 0, isActive: true, createdAt: '2026-01-01T10:00:00Z' },
];

// ========== JOB POSTINGS ==========
export const mockJobPostings: JobPosting[] = [
  {
    id: 'job-001', title: 'Senior Full-Stack Developer', company: 'Shopify', companyLogo: '/career-mentorship.png',
    location: 'Toronto, ON', province: 'Ontario', salaryMin: 120000, salaryMax: 160000, salaryPeriod: 'yearly',
    jobType: 'full_time', category: 'Developer',
    description: 'We are looking for a Senior Full-Stack Developer to join our Merchant Platform team. You will build scalable commerce solutions used by millions of merchants worldwide.',
    requirements: '5+ years full-stack experience, React/TypeScript, Ruby on Rails or Node.js, cloud infrastructure (GCP/AWS), strong testing practices.',
    responsibilities: 'Design and build merchant-facing features, mentor junior engineers, participate in on-call rotations, drive technical decisions.',
    contactEmail: 'careers@shopify.com', applyUrl: '#',
    tags: ['React', 'TypeScript', 'Node.js', 'Remote-Friendly'],
    isFeatured: true, isActive: true,
    postedAt: '2026-04-10T10:00:00Z', expiresAt: '2026-05-10T10:00:00Z', createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'job-002', title: 'Staff Accountant', company: 'Sharma & Associates CPA', companyLogo: '/finance_bg.png',
    location: 'Toronto, ON', province: 'Ontario', salaryMin: 65000, salaryMax: 85000, salaryPeriod: 'yearly',
    jobType: 'full_time', category: 'Accounting',
    description: 'Join our award-winning CPA firm as a Staff Accountant. You will work with a diverse client base including newcomers and small businesses across the GTA.',
    requirements: 'CPA designation or pursuing, 2+ years public accounting experience, proficiency in QuickBooks and TaxPrep, bilingual (English/Hindi) preferred.',
    responsibilities: 'Prepare personal and corporate tax returns, manage bookkeeping for clients, assist with CRA audits, mentor junior staff.',
    contactEmail: 'hr@sharmacpa.ca', applyUrl: '#',
    tags: ['CPA', 'Tax', 'QuickBooks'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-08T10:00:00Z', expiresAt: '2026-05-08T10:00:00Z', createdAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'job-003', title: 'iOS Developer', company: 'RBC Technology', companyLogo: '/hero-community.png',
    location: 'Toronto, ON', province: 'Ontario', salaryMin: 95000, salaryMax: 130000, salaryPeriod: 'yearly',
    jobType: 'full_time', category: 'Technology',
    description: 'RBC is looking for an experienced iOS Developer to help build the next generation of our mobile banking platform serving millions of Canadians.',
    requirements: '3+ years iOS development with Swift, experience with UIKit and SwiftUI, familiarity with CI/CD pipelines, understanding of financial services compliance.',
    responsibilities: 'Develop and maintain iOS applications, implement new features, collaborate with cross-functional teams, ensure code quality through testing.',
    contactEmail: 'techcareers@rbc.com', applyUrl: '#',
    tags: ['Swift', 'iOS', 'Banking', 'SwiftUI'],
    isFeatured: true, isActive: true,
    postedAt: '2026-04-12T10:00:00Z', expiresAt: '2026-05-12T10:00:00Z', createdAt: '2026-04-12T10:00:00Z',
  },
  {
    id: 'job-004', title: 'Registered Nurse (RN)', company: 'Sunnybrook Health Sciences', companyLogo: '/healthcare_bg.png',
    location: 'Toronto, ON', province: 'Ontario', salaryMin: 38, salaryMax: 52, salaryPeriod: 'hourly',
    jobType: 'full_time', category: 'Medical',
    description: 'Sunnybrook is seeking a Registered Nurse for our Emergency Department. Join one of Canada\'s premier academic health centres.',
    requirements: 'BScN degree, registered with CNO, current BCLS certification, 2+ years acute care experience, strong communication skills.',
    responsibilities: 'Provide direct patient care, triage and assessment, administer medications, collaborate with interdisciplinary team, document patient progress.',
    contactEmail: 'nurse.recruitment@sunnybrook.ca', applyUrl: '#',
    tags: ['Nursing', 'Emergency', 'Healthcare'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-05T10:00:00Z', expiresAt: '2026-05-05T10:00:00Z', createdAt: '2026-04-05T10:00:00Z',
  },
  {
    id: 'job-005', title: 'Front-End Web Developer', company: 'CloudBridge Solutions', companyLogo: '/career-mentorship.png',
    location: 'Remote — Canada', province: 'Ontario', salaryMin: 80000, salaryMax: 110000, salaryPeriod: 'yearly',
    jobType: 'freelance', category: 'Developer',
    description: 'We are hiring a freelance Front-End Developer for a 6-month project building a SaaS reporting dashboard for a fintech client.',
    requirements: 'Strong React/Next.js skills, TypeScript, Tailwind CSS or vanilla CSS mastery, experience with chart libraries (Recharts/D3).',
    responsibilities: 'Build responsive dashboard UI, integrate with REST APIs, implement data visualization components, ensure accessibility compliance.',
    contactEmail: 'hello@cloudbridge.ca', applyUrl: '#',
    tags: ['React', 'Next.js', 'Freelance', 'Remote'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-14T10:00:00Z', expiresAt: '2026-05-14T10:00:00Z', createdAt: '2026-04-14T10:00:00Z',
  },
  {
    id: 'job-006', title: 'Marketing Coordinator', company: 'Maple Leaf Immigration', companyLogo: '/toronto-skyline.png',
    location: 'Toronto, ON', province: 'Ontario', salaryMin: 50000, salaryMax: 65000, salaryPeriod: 'yearly',
    jobType: 'full_time', category: 'Marketing',
    description: 'Help us grow our brand! We are looking for a creative Marketing Coordinator to manage content, social media, and client engagement campaigns.',
    requirements: '2+ years marketing experience, proficiency with social media platforms, basic graphic design skills (Canva/Figma), excellent written English.',
    responsibilities: 'Plan and execute digital marketing campaigns, manage social media accounts, create marketing collateral, track campaign analytics.',
    contactEmail: 'careers@mapleleafimmigration.ca', applyUrl: '#',
    tags: ['Marketing', 'Social Media', 'Content'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-06T10:00:00Z', expiresAt: '2026-05-06T10:00:00Z', createdAt: '2026-04-06T10:00:00Z',
  },
  {
    id: 'job-007', title: 'Restaurant Manager', company: 'Spice Garden Toronto', companyLogo: '/event_bg.png',
    location: 'Mississauga, ON', province: 'Ontario', salaryMin: 55000, salaryMax: 70000, salaryPeriod: 'yearly',
    jobType: 'full_time', category: 'Restaurants',
    description: 'Spice Garden is looking for an experienced Restaurant Manager to oversee daily operations of our popular South Indian restaurant in Mississauga.',
    requirements: '3+ years restaurant management, SMART Serve certified, strong customer service skills, experience with POS systems, bilingual preferred.',
    responsibilities: 'Manage front-of-house staff, ensure food quality standards, handle customer relations, manage inventory and ordering, maintain health code compliance.',
    contactEmail: 'careers@spicegarden.ca', applyUrl: '#',
    tags: ['Hospitality', 'Management', 'F&B'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-03T10:00:00Z', expiresAt: '2026-05-03T10:00:00Z', createdAt: '2026-04-03T10:00:00Z',
  },
  {
    id: 'job-008', title: 'Data Analyst Intern', company: 'Amazon Canada', companyLogo: '/hero-community.png',
    location: 'Vancouver, BC', province: 'British Columbia', salaryMin: 25, salaryMax: 35, salaryPeriod: 'hourly',
    jobType: 'internship', category: 'Technology',
    description: 'Amazon Canada is offering a 4-month Data Analyst internship for students and recent graduates. Work on real-world datasets and gain hands-on experience.',
    requirements: 'Pursuing or completed degree in CS/Stats/Math, SQL proficiency, Python (Pandas, NumPy), familiarity with Tableau or Power BI.',
    responsibilities: 'Analyze large datasets, build dashboards, present insights to stakeholders, automate reporting workflows, collaborate with senior analysts.',
    contactEmail: 'internships@amazon.ca', applyUrl: '#',
    tags: ['Data', 'Python', 'Internship', 'SQL'],
    isFeatured: true, isActive: true,
    postedAt: '2026-04-15T10:00:00Z', expiresAt: '2026-05-15T10:00:00Z', createdAt: '2026-04-15T10:00:00Z',
  },
  {
    id: 'job-009', title: 'Part-Time Bookkeeper', company: 'NorthStar Insurance', companyLogo: '/finance_bg.png',
    location: 'Markham, ON', province: 'Ontario', salaryMin: 22, salaryMax: 28, salaryPeriod: 'hourly',
    jobType: 'part_time', category: 'Accounting',
    description: 'NorthStar Insurance is hiring a part-time bookkeeper to manage accounts payable/receivable and assist with monthly financial reporting.',
    requirements: 'Bookkeeping diploma or equivalent, experience with QuickBooks Online, attention to detail, 20-25 hours/week availability.',
    responsibilities: 'Process invoices and payments, reconcile bank statements, prepare monthly reports, maintain financial records, assist with year-end audit preparation.',
    contactEmail: 'hr@northstarinsurance.ca', applyUrl: '#',
    tags: ['Bookkeeping', 'QuickBooks', 'Part-Time'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-01T10:00:00Z', expiresAt: '2026-05-01T10:00:00Z', createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'job-010', title: 'UX/UI Designer', company: 'CloudBridge Solutions', companyLogo: '/career-mentorship.png',
    location: 'Remote — Canada', province: 'Ontario', salaryMin: 85000, salaryMax: 115000, salaryPeriod: 'yearly',
    jobType: 'contract', category: 'Design',
    description: 'CloudBridge is hiring a UX/UI Designer on a 12-month contract to lead design for our enterprise SaaS products. Fully remote.',
    requirements: 'Portfolio demonstrating SaaS/enterprise design, proficiency in Figma, experience with design systems, understanding of accessibility standards (WCAG).',
    responsibilities: 'Lead UX research and design for enterprise products, create wireframes and prototypes, maintain design system, conduct user testing sessions.',
    contactEmail: 'hello@cloudbridge.ca', applyUrl: '#',
    tags: ['Figma', 'UX', 'Design System', 'Remote'],
    isFeatured: false, isActive: true,
    postedAt: '2026-04-11T10:00:00Z', expiresAt: '2026-05-11T10:00:00Z', createdAt: '2026-04-11T10:00:00Z',
  },
];
